// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYjRuxWXevHMKy9_4B5plRO5BenIA9QKY',
    appId: '1:1031348011081:web:4434a39c5ccce135de3f98',
    messagingSenderId: '1031348011081',
    projectId: 'nostranonfe',
    authDomain: 'nostranonfe.firebaseapp.com',
    storageBucket: 'nostranonfe.appspot.com',
    measurementId: 'G-151GLSBKDJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLrCvYTdhItNRp9TjPUQgLs0hjEsXzqxc',
    appId: '1:1031348011081:android:cc0b65d7768c90dede3f98',
    messagingSenderId: '1031348011081',
    projectId: 'nostranonfe',
    storageBucket: 'nostranonfe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqA8Yw36NHqZ-I-fCPxS0exOMiyV3f_6Y',
    appId: '1:1031348011081:ios:adfd01fe36895b6dde3f98',
    messagingSenderId: '1031348011081',
    projectId: 'nostranonfe',
    storageBucket: 'nostranonfe.appspot.com',
    iosClientId: '1031348011081-uue8e3jjbdl8rkk7aa0hrsr6c8arfr2r.apps.googleusercontent.com',
    iosBundleId: 'com.example.nostranonfe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqA8Yw36NHqZ-I-fCPxS0exOMiyV3f_6Y',
    appId: '1:1031348011081:ios:adfd01fe36895b6dde3f98',
    messagingSenderId: '1031348011081',
    projectId: 'nostranonfe',
    storageBucket: 'nostranonfe.appspot.com',
    iosClientId: '1031348011081-uue8e3jjbdl8rkk7aa0hrsr6c8arfr2r.apps.googleusercontent.com',
    iosBundleId: 'com.example.nostranonfe',
  );
}
